using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Contractor.Ui;

[GenerateTypedNameReferences]
public sealed partial class ContractorAcceptWindow : FancyWindow
{
    public event Action? OnAccept;
    public event Action? OnDeny;

    public ContractorAcceptWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        DenyButton.OnPressed += _ => OnDeny?.Invoke();
    }
}
