using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Miners;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Miners.UI;

[GenerateTypedNameReferences]
public sealed partial class MinersBountyRedemptionMenu : FancyWindow
{
    public Action? SellRequested;

    public MinersBountyRedemptionMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }
}
