using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Miners;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Miners.UI;

[GenerateTypedNameReferences]
public sealed partial class MinersBountyMenu : FancyWindow
{
    public Action<string>? OnLabelButtonPressed;
    public Action<string>? OnSkipButtonPressed;

    public MinersBountyMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<MinersBountyData> bounties, TimeSpan untilNextSkip)
    {
        MinersBountyEntriesContainer.Children.Clear();
        foreach (var b in bounties)
        {
            var entry = new MinersBountyEntry(b, untilNextSkip);
            entry.OnLabelButtonPressed += () => OnLabelButtonPressed?.Invoke(b.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(b.Id);

            MinersBountyEntriesContainer.AddChild(entry);
        }
        MinersBountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
