using Content.Client.UserInterface.Controls;
using Content.Shared.Corvax.Mercenary;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Corvax.Mercenary.UI;

[GenerateTypedNameReferences]
public sealed partial class MercenaryBountyRedemptionMenu : FancyWindow
{
    public Action? SellRequested;

    public MercenaryBountyRedemptionMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }
}
