using Content.Client.UserInterface.Controls;
using Content.Shared.Corvax.Mercenary;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Corvax.Mercenary.UI;

[GenerateTypedNameReferences]
public sealed partial class MercenaryBountyMenu : FancyWindow
{
    public Action<string>? OnLabelButtonPressed;
    public Action<string>? OnSkipButtonPressed;

    public MercenaryBountyMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<MercenaryBountyData> bounties, TimeSpan untilNextSkip)
    {
        MercenaryBountyEntriesContainer.Children.Clear();
        foreach (var b in bounties)
        {
            var entry = new MercenaryBountyEntry(b, untilNextSkip);
            entry.OnLabelButtonPressed += () => OnLabelButtonPressed?.Invoke(b.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(b.Id);

            MercenaryBountyEntriesContainer.AddChild(entry);
        }
        MercenaryBountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
